# Generated by Django 4.1.1 on 2023-06-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('isofficial', models.BooleanField()),
                ('iskalendaru', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('password', models.CharField(max_length=255)),
                ('date_registration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('hascompleted', models.BooleanField()),
                ('user_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kalendaruapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('hasCompleated', models.BooleanField()),
                ('user_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kalendaruapp.user')),
            ],
        ),
    ]
